### PR TITLE
SELinux

### PR DESCRIPTION
**Pull request by handymenny**

### CODE REVIEW

**Comment by handymenny** [comment]
Here there is  a part of the logs that I used to write this sepolicy: https://drive.google.com/file/d/0B5YWgdzTvL6JWnRKSGROZGxRSTg/view?usp=sharing
The most useful informations come from "/data/misc/audit/audit.log".

**Comment by Agontuk** [comment]
removing all in dhcp folder will remove dhcpcd.conf file too. Does wifi work after that? I'm thinking that dhcpcd_fix may not be needed at all.

**Comment by Agontuk** [comment]
About selinux, I found some cases where you used macros like "r_file_perms", but not all the perms listed under that macro is required. I thought we only can use those if we need all the perms under that macro. Is this OK ?

**Comment by handymenny** [comment]
Wifi works after removing all in dhcp folder, maybe the aim of dhcpcd_fix is to solve some issues with wifi direct.
I used macros to save time and make the *.te files more readable. This isn't a security issue as google and nsa suggest to do that.

**Comment by Agontuk** [comment]
Merged manually cause I don't want to merge fota commits. We're fine without it, so no need for now.

**Comment by handymenny** [comment]
Sorry, I forgot that github automatically adds new commits to the pull requests.
Remember that users must wipe data and must not restore selinux contexts on /data.

**Comment by Agontuk** [comment]
I recently noticed you didn't add all policy files in BOARD_POLICY_UNION. Is there any specific reason ?

**Comment by handymenny** [comment]
The others are already included in vendor/cm/sepolicy/sepolicy.mk
https://github.com/CyanogenMod/android_vendor_cm/blob/cm-12.1/sepolicy/sepolicy.mk#L9-L39

**Pull request closed without merging**
