### PR TITLE
During regular boot remove busybox instead of replacing it

### PR DESCRIPTION
**Pull request by handymenny**
Change-Id: I6ee5e9a25173e1daa7a4c4d9ef155b6afad5b9f8

### CODE REVIEW

**Comment by Agontuk** [comment]
I think only removing the line from custombootimg.mk will work. Make a new pull request or change this with only that change and I'll merge it :)

**Comment by handymenny** [comment]
Yes, but /sbin/busybox isn't the equal to /system/xbin/busybox 
To keep static busybox isn't safe

**Comment by Agontuk** [comment]
After booting, it's of no use to us anymore since we're removing all symlinks from sbin. System doesn't call busybox, it only tries to access those symlinks. So if they're not in sbin, it'll try to find them in system/bin or system/xbin; which uses dynamic busybox. So we're safe. Also all sony device uses it like this, so no worry ;)

**Comment by handymenny** [comment]
Checked all symlinks point directly to /system/xbin/busybox
I'll make a new pull request.

**Pull request closed without merging**
