### PR TITLE
Get rid of postrecoveryboot/usbid_init

### PR DESCRIPTION
**Pull request by handymenny**

### CODE REVIEW

**Comment by Agontuk** [comment]
I already have usbid_init changes in my local repo, but it's different.
About cleanup, I don't think ifup and ifconfig does the same thing. I'll take a look.

**Comment by handymenny** [comment]
Can you tell me with what have you replaced ubid_init.sh? I'm curious.

AFAIK "ifup < interface >" is equivalent to "ifconfig < interface > up", another aim of this change is to improve the compatibility with SELinux. See: https://github.com/android/platform_system_core/blob/lollipop-release/init/readme.txt#L149-150

**Comment by Agontuk** [comment]
Sorry, i was sick for some days. I'll test it then merge if it's ok

**Comment by handymenny** [comment]
Don't worry, take your time.
EDIT: However usb doesn't seem to work very well. ( In recovery it's working fine )

**Comment by handymenny** [comment]
The issue that I'm experiencing isn't related to this change.
I have reverted this change in my local repo (and I have also flashed the default kernel), MTP still doesn't work.

**Comment by Agontuk** [comment]
What do you mean? Storage is not showing up? In windows ?

**Comment by Agontuk** [comment]
I cherry-picked the usb commit and made some changes. I'll push it now and close the pull request. I'm still not sure about the ifconfig and ifup, so I'll let it unchanged for now

**Pull request closed without merging**
