### PR TITLE
SELinux

### PR DESCRIPTION
**Pull request by handymenny**

### CODE REVIEW

**Comment by handymenny** [comment]
I'm running in enforcing mode from days and I don't see any significant denial in /data/audit.log
To test this policy you need to wipe data and restore contexts on /system (if you don't make a full build)

**Comment by Agontuk** [comment]
Thanks man, I'll take a look later. I'm busy with Bluetooth right now.

**Comment by handymenny** [comment]
I've updated the pull request. This is the diff: https://gist.github.com/HandyMenny/41db5e2cc74887a39282

**Comment by Agontuk** [comment]
Haven't got time to check all the things yet. I'm thinking of switching to f2fs filesystem, so selinux policy would need some changes as well. I'll inform you when it's done.

**Comment by handymenny** [comment]
FYI switching to f2fs doesn't need additional rules, I've tested with /data formatted with f2fs. 
IMHO Format /system with f2fs is useless as ext4 seems more fast in reading.
For /cache I suggest you to not change his filesystem, a wrong filesystem could prevent the boot up of the recovery.
There are other changes that this sepolicy requires, mainly related to camcorder.
I can suggest you to switch to f2fs and enable selinux in the same build, in order to force users to do a full wipe.

**Comment by handymenny** [comment]
Here you can find the patches that I applied:
https://github.com/HandyMenny/android_device_sony_kumquat/commit/945ccebda73190068a51f6fa826d904a23e3e950
https://github.com/HandyMenny/android_kernel_sony_u8500/commits/f2fs

**Comment by handymenny** [comment]
I'll make a new pull request on cm-12.1 branch after checking how this sepolicy behaves on cm-12.1.

**Comment by Agontuk** [comment]
OK, I'm also thinking about building 1st cm-12.1 with selinux enabled. For now, I'm updating the patches.

**Pull request closed without merging**
